version: "2.3"

services:
  # micros docekr image build
  roscore:
      image: ros:noetic-ros-core-focal
      # build:
      #   context: .
      #   dockerfile: Dockerfile.ros2.micro_ros
      environment:
        - "ROS_DOMAIN_ID=0"
        - "ROS_IP=192.168.29.3"
        - "ROS_MASTER_URI=http://192.168.29.3:11311"
      command: bash -c "roscore &"
      # devices:
      #   - /octo
      tty: true
      privileged: false
      network_mode: host
      # extra_hosts:
      #   - octo:192.168.29.3"
      ipc: host
      restart: unless-stopped
